version: '3.8'

services:
  bot:
    build: .
    container_name: bot-coupons
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "coupon.main"]
